# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cve_gui_v4.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from collraborate import CollaborateSystem
from PyQt5.QtWidgets import QFileDialog


class Ui_MainWindow(object):
    index = 0
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(625, 395)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setEnabled(True)
        self.stackedWidget.setObjectName("stackedWidget")
        self.main_page = QtWidgets.QWidget()
        self.main_page.setObjectName("main_page")
        self.pushButton = QtWidgets.QPushButton(self.main_page)
        self.pushButton.setGeometry(QtCore.QRect(130, 300, 341, 61))
        self.pushButton.setObjectName("pushButton")
        self.mainLabel = QtWidgets.QLabel(self.main_page)
        self.mainLabel.setGeometry(QtCore.QRect(50, 30, 500, 230))
        self.mainLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.mainLabel.setObjectName("mainLabel")
        self.stackedWidget.addWidget(self.main_page)
        self.binary_page = QtWidgets.QWidget()
        self.binary_page.setObjectName("binary_page")
        self.selectBinaryButton = QtWidgets.QPushButton(self.binary_page)
        self.selectBinaryButton.setGeometry(QtCore.QRect(440, 270, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.selectBinaryButton.setFont(font)
        self.selectBinaryButton.setObjectName("selectBinaryButton")
        self.binaryPath = QtWidgets.QTextEdit(self.binary_page)
        self.binaryPath.setGeometry(QtCore.QRect(60, 270, 371, 41))
        self.binaryPath.setObjectName("binaryPath")
        self.goAlgoBtn = QtWidgets.QPushButton(self.binary_page)
        self.goAlgoBtn.setGeometry(QtCore.QRect(450, 340, 99, 27))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.goAlgoBtn.setFont(font)
        self.goAlgoBtn.setObjectName("goAlgoBtn")
        self.binaryLabel = QtWidgets.QLabel(self.binary_page)
        self.binaryLabel.setGeometry(QtCore.QRect(150, 20, 300, 45))
        self.binaryLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.binaryLabel.setObjectName("binaryLabel")
        self.binaryTopicImg = QtWidgets.QLabel(self.binary_page)
        self.binaryTopicImg.setGeometry(QtCore.QRect(5, 20, 600, 50))
        self.binaryTopicImg.setText("")
        self.binaryTopicImg.setPixmap(QtGui.QPixmap("./image/topic.png"))
        self.binaryTopicImg.setObjectName("binaryTopicImg")
        self.binaryLabel_2 = QtWidgets.QLabel(self.binary_page)
        self.binaryLabel_2.setGeometry(QtCore.QRect(60, 200, 370, 40))
        self.binaryLabel_2.setObjectName("binaryLabel_2")
        self.selectBinaryButton.raise_()
        self.binaryPath.raise_()
        self.goAlgoBtn.raise_()
        self.binaryTopicImg.raise_()
        self.binaryLabel.raise_()
        self.binaryLabel_2.raise_()
        self.stackedWidget.addWidget(self.binary_page)
        self.algorithm_page = QtWidgets.QWidget()
        self.algorithm_page.setObjectName("algorithm_page")
        self.goDataBtn = QtWidgets.QPushButton(self.algorithm_page)
        self.goDataBtn.setGeometry(QtCore.QRect(450, 340, 99, 27))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.goDataBtn.setFont(font)
        self.goDataBtn.setObjectName("goDataBtn")
        self.BackBinaryBtn = QtWidgets.QPushButton(self.algorithm_page)
        self.BackBinaryBtn.setGeometry(QtCore.QRect(340, 340, 99, 27))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.BackBinaryBtn.setFont(font)
        self.BackBinaryBtn.setObjectName("BackBinaryBtn")
        self.scrollArea = QtWidgets.QScrollArea(self.algorithm_page)
        self.scrollArea.setGeometry(QtCore.QRect(30, 100, 550, 200))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 548, 198))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.addAlgoWidgetContent = QtWidgets.QWidget(self.algorithm_page)
        self.addAlgoWidgetContent.setGeometry(QtCore.QRect(30, 80, 550, 250))
        self.addAlgoWidgetContent.setObjectName("addAlgoWidgetContent")
        self.addAlgoWidgetContent.hide()
        self.gridLayout_4 = QtWidgets.QGridLayout(self.addAlgoWidgetContent)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.addAlgoArea = QtWidgets.QScrollArea(self.addAlgoWidgetContent)
        self.addAlgoArea.setWidgetResizable(True)
        self.addAlgoArea.setObjectName("addAlgoArea")
        self.addAlgowidget = QtWidgets.QWidget()
        self.addAlgowidget.setGeometry(QtCore.QRect(0, 0, 530, 230))
        self.addAlgowidget.setObjectName("addAlgowidget")
        self.addAlgoPath = QtWidgets.QTextEdit(self.addAlgowidget)
        self.addAlgoPath.setGeometry(QtCore.QRect(130, 170, 261, 41))
        self.addAlgoPath.setObjectName("addAlgoPath")
        self.addAgloBtn = QtWidgets.QPushButton(self.addAlgowidget)
        self.addAgloBtn.setGeometry(QtCore.QRect(410, 120, 101, 51))
        self.addAgloBtn.setObjectName("addAgloBtn")
        self.addAlgoName = QtWidgets.QTextEdit(self.addAlgowidget)
        self.addAlgoName.setGeometry(QtCore.QRect(130, 120, 261, 41))
        self.addAlgoName.setObjectName("addAlgoName")
        self.addAlgoCancelBtn = QtWidgets.QPushButton(self.addAlgowidget)
        self.addAlgoCancelBtn.setGeometry(QtCore.QRect(410, 180, 101, 31))
        self.addAlgoCancelBtn.setObjectName("addAlgoCancelBtn")
        self.label = QtWidgets.QLabel(self.addAlgowidget)
        self.label.setGeometry(QtCore.QRect(20, 120, 100, 40))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.addAlgowidget)
        self.label_2.setGeometry(QtCore.QRect(20, 170, 100, 40))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.addAlgowidget)
        self.label_3.setGeometry(QtCore.QRect(10, 70, 471, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setItalic(False)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.addAlgoArea.setWidget(self.addAlgowidget)
        self.gridLayout_4.addWidget(self.addAlgoArea, 0, 0, 1, 1)
        self.algoLabel = QtWidgets.QLabel(self.algorithm_page)
        self.algoLabel.setGeometry(QtCore.QRect(150, 20, 300, 45))
        self.algoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.algoLabel.setObjectName("algoLabel")
        self.algoTopicLabel = QtWidgets.QLabel(self.algorithm_page)
        self.algoTopicLabel.setGeometry(QtCore.QRect(5, 20, 600, 50))
        self.algoTopicLabel.setText("")
        self.algoTopicLabel.setPixmap(QtGui.QPixmap("./image/topic.png"))
        self.algoTopicLabel.setObjectName("algoTopicLabel")
        self.waitLearning = QtWidgets.QWidget(self.algorithm_page)
        self.waitLearning.setGeometry(QtCore.QRect(5, 10, 600, 300))
        self.waitLearning.setObjectName("waitLearning")
        self.waitLearning.hide()
        self.gridLayout_8 = QtWidgets.QGridLayout(self.waitLearning)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.waitLearning)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.gridLayout_8.addWidget(self.textBrowser_2, 0, 0, 1, 1)
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.waitLearning)
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.gridLayout_8.addWidget(self.textBrowser_3, 1, 0, 1, 1)
        self.goDataBtn.raise_()
        self.BackBinaryBtn.raise_()
        self.scrollArea.raise_()
        self.addAlgoWidgetContent.raise_()
        self.algoTopicLabel.raise_()
        self.algoLabel.raise_()
        self.waitLearning.raise_()
        self.stackedWidget.addWidget(self.algorithm_page)
        self.dataset_page = QtWidgets.QWidget()
        self.dataset_page.setObjectName("dataset_page")
        self.goResultBtn = QtWidgets.QPushButton(self.dataset_page)
        self.goResultBtn.setGeometry(QtCore.QRect(450, 340, 99, 27))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.goResultBtn.setFont(font)
        self.goResultBtn.setObjectName("goResultBtn")
        self.BackAlgoBtn = QtWidgets.QPushButton(self.dataset_page)
        self.BackAlgoBtn.setGeometry(QtCore.QRect(340, 340, 99, 27))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.BackAlgoBtn.setFont(font)
        self.BackAlgoBtn.setObjectName("BackAlgoBtn")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.dataset_page)
        self.scrollArea_2.setGeometry(QtCore.QRect(30, 100, 550, 200))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 548, 198))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_3)
        self.addDataWidgetContent = QtWidgets.QWidget(self.dataset_page)
        self.addDataWidgetContent.setGeometry(QtCore.QRect(30, 70, 550, 250))
        self.addDataWidgetContent.setObjectName("addDataWidgetContent")
        self.addDataWidgetContent.hide()
        self.gridLayout_5 = QtWidgets.QGridLayout(self.addDataWidgetContent)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.addDataArea = QtWidgets.QScrollArea(self.addDataWidgetContent)
        self.addDataArea.setWidgetResizable(True)
        self.addDataArea.setObjectName("addDataArea")
        self.addDatawidget = QtWidgets.QWidget()
        self.addDatawidget.setGeometry(QtCore.QRect(0, 0, 530, 230))
        self.addDatawidget.setObjectName("addDatawidget")
        self.addDataName = QtWidgets.QTextEdit(self.addDatawidget)
        self.addDataName.setGeometry(QtCore.QRect(150, 120, 241, 41))
        self.addDataName.setObjectName("addDataName")
        self.addDataBtn = QtWidgets.QPushButton(self.addDatawidget)
        self.addDataBtn.setGeometry(QtCore.QRect(410, 120, 101, 51))
        self.addDataBtn.setObjectName("addDataBtn")
        self.addDataPath = QtWidgets.QTextEdit(self.addDatawidget)
        self.addDataPath.setGeometry(QtCore.QRect(150, 170, 241, 41))
        self.addDataPath.setObjectName("addDataPath")
        self.pushButton_2 = QtWidgets.QPushButton(self.addDatawidget)
        self.pushButton_2.setGeometry(QtCore.QRect(410, 180, 100, 30))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_4 = QtWidgets.QLabel(self.addDatawidget)
        self.label_4.setGeometry(QtCore.QRect(20, 120, 100, 40))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.addDatawidget)
        self.label_5.setGeometry(QtCore.QRect(20, 180, 100, 40))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.addDatawidget)
        self.label_6.setGeometry(QtCore.QRect(10, 70, 400, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setItalic(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.addDataArea.setWidget(self.addDatawidget)
        self.gridLayout_5.addWidget(self.addDataArea, 0, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.dataset_page)
        self.label_7.setGeometry(QtCore.QRect(150, 20, 300, 45))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.dataset_page)
        self.label_8.setGeometry(QtCore.QRect(5, 20, 600, 50))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("./image/topic.png"))
        self.label_8.setObjectName("label_8")
        self.goResultBtn.raise_()
        self.BackAlgoBtn.raise_()
        self.scrollArea_2.raise_()
        self.addDataWidgetContent.raise_()
        self.label_8.raise_()
        self.label_7.raise_()
        self.stackedWidget.addWidget(self.dataset_page)
        self.result_page = QtWidgets.QWidget()
        self.result_page.setObjectName("result_page")
        self.resultText = QtWidgets.QTextEdit(self.result_page)
        self.resultText.setGeometry(QtCore.QRect(10, 70, 581, 261))
        self.resultText.setObjectName("resultText")
        self.pushButton_4 = QtWidgets.QPushButton(self.result_page)
        self.pushButton_4.setGeometry(QtCore.QRect(450, 340, 99, 27))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.ResultWidget = QtWidgets.QWidget(self.dataset_page)
        self.ResultWidget.setGeometry(QtCore.QRect(-10, 10, 611, 371))
        self.ResultWidget.setObjectName("ResultWidget")
        self.ResultWidget.hide()
        self.gridLayout_3 = QtWidgets.QGridLayout(self.ResultWidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.textBrowser = QtWidgets.QTextBrowser(self.ResultWidget)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout_3.addWidget(self.textBrowser, 0, 0, 1, 1)
        self.ResultWidget.raise_()
        self.label_9 = QtWidgets.QLabel(self.result_page)
        self.label_9.setGeometry(QtCore.QRect(150, 20, 300, 45))
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.result_page)
        self.label_10.setGeometry(QtCore.QRect(5, 20, 600, 50))
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("./image/topic.png"))
        self.label_10.setObjectName("label_10")
        self.resultText.raise_()
        self.pushButton_4.raise_()
        self.label_10.raise_()
        self.label_9.raise_()
        self.stackedWidget.addWidget(self.result_page)
        self.gridLayout_7.addWidget(self.stackedWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.setBtnSignal()
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "START"))
        self.mainLabel.setText(_translate("MainWindow", "\n"
"\n"
"ML - CVE\n"
"Machine Learning\n"
"Collaborative Vulnerability Explorer"))
        self.selectBinaryButton.setText(_translate("MainWindow", "Find"))
        self.binaryPath.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:20pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.goAlgoBtn.setText(_translate("MainWindow", "Next"))
        self.binaryLabel.setText(_translate("MainWindow", "Select binary File"))
        self.binaryLabel_2.setText(_translate("MainWindow", "Set Binary File Path"))
        self.goDataBtn.setText(_translate("MainWindow", "Next"))
        self.BackBinaryBtn.setText(_translate("MainWindow", "Back"))
        self.addAgloBtn.setText(_translate("MainWindow", "OK"))
        self.addAlgoCancelBtn.setText(_translate("MainWindow", "Close"))
        self.label.setText(_translate("MainWindow", "Name"))
        self.label_2.setText(_translate("MainWindow", "Image"))
        self.label_3.setText(_translate("MainWindow", "Please set image name and specify the path"))
        self.algoLabel.setText(_translate("MainWindow", "Select Algorithm"))
        self.textBrowser_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:20pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Learning Algorithm..</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Please Wait..</p></body></html>"))
        self.textBrowser_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:20pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/loading.gif\" /></p></body></html>"))
        self.goResultBtn.setText(_translate("MainWindow", "Next"))
        self.BackAlgoBtn.setText(_translate("MainWindow", "Back"))
        self.addDataBtn.setText(_translate("MainWindow", "OK"))
        self.pushButton_2.setText(_translate("MainWindow", "Close"))
        self.label_4.setText(_translate("MainWindow", "Name"))
        self.label_5.setText(_translate("MainWindow", "DataSet"))
        self.label_6.setText(_translate("MainWindow", "Please specify the path to the Dataset"))
        self.label_7.setText(_translate("MainWindow", "Select Dataset"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:20pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Producing Result....</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">....</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">....</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Wait For Seconds....</span></p></body></html>"))
        self.pushButton_4.setText(_translate("MainWindow", "EXIT"))
        self.label_9.setText(_translate("MainWindow", "Result"))

    def nextWidgetWindow(self):
        self.index = self.index +1
        ui.stackedWidget.setCurrentIndex(self.index)

    def preWidgetWindow(self):
        self.index = self.index -1
        ui.stackedWidget.setCurrentIndex(self.index)

    def exitProgram(self):
       sys.exit()

    def pushButtonClicked(self):
        file_name = QFileDialog.getOpenFileName(self, 'Open File', os.getenv('HOME'))
        #self.label.setText(fname[0])

    def addAlgoFun(self):
        self.addAlgoWidgetContent.show()

    def closeAddAlgo(self):
        self.addAlgoWidgetContent.hide()

    def addDataFun(self):
        self.addDataWidgetContent.show()

    def closeAddData(self):
        self.addAlgoWidgetContent.hide()

    def addBinaryBtn(self):
        filename = QFileDialog.getOpenFileName()
        self.binaryPath.setText(filename[0])

    def setBtnSignal(self):
        self.pushButton.clicked.connect(self.nextWidgetWindow)
        self.goAlgoBtn.clicked.connect(self.nextWidgetWindow)
        self.goDataBtn.clicked.connect(self.nextWidgetWindow)
        self.goResultBtn.clicked.connect(self.nextWidgetWindow)
        self.BackBinaryBtn.clicked.connect(self.preWidgetWindow)
        self.BackAlgoBtn.clicked.connect(self.preWidgetWindow)
        self.pushButton_4.clicked.connect(self.exitProgram)
        self.selectBinaryButton.clicked.connect(self.addBinaryBtn)
        self.addAlgoCancelBtn.clicked.connect(self.closeAddAlgo)
        self.pushButton_2.clicked.connect(self.closeAddData)


#import image_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    cs = CollaborateSystem(ui)
    cs.setUP()
    MainWindow.show()
    ui.goResultBtn.clicked.connect(cs.Click_Print_Result)
    sys.exit(app.exec_())
